# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Mendix Documentation

on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches: 
      - development

env:
    GET_ENV_VAR: ./_scripts/get_env.sh
    GOPATH: "${HOME}/.go_workspace"
    HUGO_ENV: $($GET_ENV_VAR)
    CF_APP: docs
    CF_API: https://api.run.pivotal.io
    CF_USERNAME: jelte.lagendijk@mendix.com
    CF_ORGANIZATION: mendix-rnd.com
    CF_SPACE: docs
    CF_CLI_VERSION: 6.22.2
    HUGO_VERSION: 0.31.1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:

    - name: Set up Node.js
    - run: echo "These are the examples ones"
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Before install
      run: |
        echo "$HOME" >> $GITHUB_PATH
        echo "HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit" >> $GITHUB_ENV
        curl -L https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
        chmod +x ./hugo
        mv ./hugo $HOME/bin/hugo

    - name: install
    - run: |
        rm -rf _site
        yarn install

    - name: Before Deploying
      run: |
        echo "$HOME" >> $GITHUB_PATH
        curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
        tar xzvf $HOME/cf.tgz -C $HOME
        chmod +x $HOME/cf
        mv $HOME/cf $HOME/bin/cf
        cp ./_scripts/autopilot-linux $HOME/
        chmod a+x $HOME/autopilot-linux
        ./_scripts/before_deploy.sh

    - name: Gulp Build
      run: ./node_modules/.bin/gulp build

    - name: Deploy
      run: echo "Deploying for development or master"
      if: github.ref == 'ref/head/development' || github.ref == 'ref/head/master'


# Original examples
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test

