# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Mendix Documentation

on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches: 
      - development

env:
    GET_ENV_VAR: ./_scripts/get_env.sh
    GOPATH: "$HOME/.go_workspace"
    HUGO_ENV: test
    CF_APP: docs
    CF_API: https://api.run.pivotal.io
    CF_USERNAME: jelte.lagendijk@mendix.com
    CF_ORGANIZATION: mendix-rnd.com
    CF_SPACE: docs
    CF_CLI_VERSION: 6.22.2
    HUGO_VERSION: 0.31.1
    HUGO_PACKAGE: hugo_0.31.1_Linux-64bit
    TRAVIS_BRANCH: ${GITHUB_REF#refs/*/}
    TRAVIS_PULL_REQUEST: ${GITHUB_EVENT_NAME == "pull request"}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check environment variables
      run: |
        echo "environment variables"
        echo $GET_ENV_VAR
        echo $GOPATH
        echo $HUGO_ENV
        echo $CF_APP
        echo $CF_API
        echo $CF_USERNAME
        echo $CF_ORGANIZATION
        echo $CF_SPACE
        echo $CF_CLI_VERSION
        echo $HUGO_VERSION
        echo $HUGO_PACKAGE
        echo $GITHUB_REF
        echo $TRAVIS_BRANCH
        echo $GITHIB_EVENT_NAME
        echo $TRAVIS_PULL_REQUEST
        echo "curl -L https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz"

          
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Before install
      run: |
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz | tar xz
        chmod +x ./hugo
        mkdir -p $GITHUB_WORKSPACE/bin/hugo
        mv ./hugo $GITHUB_WORKSPACE/bin/hugo
      
    - name: install
      run: |
        rm -rf _site
        yarn install
  
    - name: Before Deploying
      run: |
        echo "$HOME" >> $GITHUB_PATH
        curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
        tar xzvf $HOME/cf.tgz -C $HOME
        chmod +x $HOME/cf
        mkdir -p $HOME/bin/cf
        mv $HOME/cf $HOME/bin/cf
        cp ./_scripts/autopilot-linux $HOME/
        chmod a+x $HOME/autopilot-linux
        ./_scripts/before_deploy.sh
        
        
