# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Mendix Documentation

on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches: 
      - development

env:
    GET_ENV_VAR: ./_scripts/get_env.sh
    GOPATH: "${HOME}/.go_workspace"
    HUGO_ENV: $($GET_ENV_VAR)
    CF_APP: docs
    CF_API: https://api.run.pivotal.io
    CF_USERNAME: jelte.lagendijk@mendix.com
    CF_ORGANIZATION: mendix-rnd.com
    CF_SPACE: docs
    CF_CLI_VERSION: 6.22.2
    HUGO_VERSION: 0.31.1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:

    - name: Hello World
      run: echo "Hello World"


